<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="3" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Login sucessfully executed]]>
    </line>
    <line>
      <![CDATA[Click to see screenshot]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Sun_Aug_19_11_09_14_IST_2018.jpg>Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Sun_Aug_19_11_09_14_IST_2018.jpg><img src=Sun_Aug_19_11_09_14_IST_2018.jpg height=200 width=200></img></a>]]>
    </line>
    <line>
      <![CDATA[Click to see screenshot]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Sun_Aug_19_11_09_15_IST_2018.jpg>Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Sun_Aug_19_11_09_15_IST_2018.jpg><img src=Sun_Aug_19_11_09_15_IST_2018.jpg height=200 width=200></img></a>]]>
    </line>
    <line>
      <![CDATA[Click to see screenshot]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Sun_Aug_19_11_09_15_IST_2018.jpg>Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Sun_Aug_19_11_09_15_IST_2018.jpg><img src=Sun_Aug_19_11_09_15_IST_2018.jpg height=200 width=200></img></a>]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="2418" started-at="2018-08-19T05:39:13Z" finished-at="2018-08-19T05:39:16Z">
    <groups>
    </groups>
    <test name="Bank Manager Test" duration-ms="622" started-at="2018-08-19T05:39:13Z" finished-at="2018-08-19T05:39:14Z">
      <class name="com.ddf.testcases.BankMangerLogin">
        <test-method status="FAIL" signature="loginAsBankManager()[pri:0, instance:com.ddf.testcases.BankMangerLogin@7a8c8dcf]" name="loginAsBankManager" duration-ms="287" started-at="2018-08-19T05:39:13Z" finished-at="2018-08-19T05:39:14Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[login not found]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: login not found
at org.junit.Assert.fail(Assert.java:88)
at com.ddf.testcases.BankMangerLogin.loginAsBankManager(BankMangerLogin.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Login sucessfully executed]]>
            </line>
            <line>
              <![CDATA[Click to see screenshot]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Sun_Aug_19_11_09_14_IST_2018.jpg>Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Sun_Aug_19_11_09_14_IST_2018.jpg><img src=Sun_Aug_19_11_09_14_IST_2018.jpg height=200 width=200></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginAsBankManager -->
      </class> <!-- com.ddf.testcases.BankMangerLogin -->
    </test> <!-- Bank Manager Test -->
    <test name="Add Customer Test" duration-ms="1734" started-at="2018-08-19T05:39:14Z" finished-at="2018-08-19T05:39:16Z">
      <class name="com.ddf.testcases.AddCustomer">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.ddf.testcases.AddCustomer@70325e14]" name="setUp" is-config="true" duration-ms="14456" started-at="2018-08-19T05:38:59Z" finished-at="2018-08-19T05:39:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="addCustomer(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.ddf.testcases.AddCustomer@70325e14]" name="addCustomer" duration-ms="652" started-at="2018-08-19T05:39:14Z" data-provider="getData" finished-at="2018-08-19T05:39:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ram]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[dash]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[6789.0]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Customer added successfully]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[customer not added sucessfully]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: customer not added sucessfully
at org.testng.Assert.fail(Assert.java:96)
at com.ddf.testcases.AddCustomer.addCustomer(AddCustomer.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Click to see screenshot]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Sun_Aug_19_11_09_15_IST_2018.jpg>Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Sun_Aug_19_11_09_15_IST_2018.jpg><img src=Sun_Aug_19_11_09_15_IST_2018.jpg height=200 width=200></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- addCustomer -->
        <test-method status="FAIL" signature="addCustomer(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.ddf.testcases.AddCustomer@70325e14]" name="addCustomer" duration-ms="303" started-at="2018-08-19T05:39:15Z" data-provider="getData" finished-at="2018-08-19T05:39:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[sam]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[df]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[44554.0]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Customer added successfully]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[customer not added sucessfully]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: customer not added sucessfully
at org.testng.Assert.fail(Assert.java:96)
at com.ddf.testcases.AddCustomer.addCustomer(AddCustomer.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Click to see screenshot]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Sun_Aug_19_11_09_15_IST_2018.jpg>Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Sun_Aug_19_11_09_15_IST_2018.jpg><img src=Sun_Aug_19_11_09_15_IST_2018.jpg height=200 width=200></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- addCustomer -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.ddf.testcases.AddCustomer@70325e14]" name="tearDown" is-config="true" duration-ms="1781" started-at="2018-08-19T05:39:16Z" finished-at="2018-08-19T05:39:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.ddf.testcases.AddCustomer -->
    </test> <!-- Add Customer Test -->
  </suite> <!-- Suite -->
</testng-results>
